# Generated by Django 5.0.3 on 2024-12-08 14:39

import datetime
import django.db.models.deletion
import django.utils.timezone
import purchases.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('needs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EZZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EZZ_number', models.CharField(max_length=20, unique=True, verbose_name='Numer EZZ')),
                ('ordering_person', models.CharField(max_length=40, verbose_name='Osoba zamawiająca')),
                ('creation_date', models.DateField(default=datetime.date(1990, 1, 1), verbose_name='Data utworzenia')),
                ('subject', models.CharField(max_length=5000, verbose_name='Temat')),
                ('status', models.CharField(max_length=40, verbose_name='Status')),
                ('suplier', models.CharField(max_length=300, null=True, verbose_name='Dostawca')),
                ('source_of_financing', models.CharField(max_length=20, verbose_name='Źródło finansowania')),
                ('final_receiver', models.CharField(max_length=30, verbose_name='Odbiorca końcowy')),
                ('current_acceptor', models.CharField(blank=True, default='', max_length=201, null=True, verbose_name='Bieżący akceptor')),
                ('date_of_last_acceptance', models.DateField(default=datetime.date(1990, 1, 1), null=True, verbose_name='Data ostatniej akceptacji')),
                ('nieistotny', models.BooleanField(blank=True, default=False, verbose_name='Nieistotny')),
            ],
            options={
                'verbose_name': 'Wniosek EZZ',
                'verbose_name_plural': 'Wnioski EZZ',
            },
        ),
        migrations.CreateModel(
            name='Postepowania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_SRM_SAP', models.CharField(max_length=21, verbose_name='Numer SRM/SAP')),
                ('numer_ZZ', models.CharField(max_length=22, verbose_name='Numer ZZ')),
                ('opis_zapotrzebowania', models.CharField(max_length=1121, verbose_name='Opis zapotrzebowania')),
                ('priorytet', models.CharField(max_length=13, null=True, verbose_name='Priorytet')),
                ('status_SRM', models.CharField(max_length=19, null=True, verbose_name='Status SRM')),
                ('zlecajacy', models.CharField(max_length=28, null=True, verbose_name='Zlecający')),
                ('kupiec', models.CharField(max_length=36, null=True, verbose_name='Kupiec')),
                ('status_biura', models.CharField(max_length=62, null=True, verbose_name='Status biura')),
                ('data_wprowadzenia', models.DateField(default=None, null=True, verbose_name='Data wprowadzenia')),
                ('connect', models.CharField(default='', max_length=40, null=True, verbose_name='Status na Conect')),
            ],
            options={
                'verbose_name': 'Postępowanie',
                'verbose_name_plural': 'Postępowania',
            },
        ),
        migrations.CreateModel(
            name='LogPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akcja', models.CharField(default=None, max_length=303, null=True, verbose_name='Akcja')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Log zakupu',
                'verbose_name_plural': 'Logi zakupów',
            },
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('przedmiot_zakupu', models.CharField(blank=True, default='', max_length=2000, verbose_name='Przedmiot zakupu')),
                ('uzasadnienie_zakupu', models.CharField(blank=True, default='', max_length=5022, verbose_name='Uzasadnienie zakupu')),
                ('zakres_zakupu', models.CharField(blank=True, default='', max_length=3001, verbose_name='Zakres zakupu')),
                ('cel_i_produkty', models.CharField(blank=True, default='', max_length=2000, verbose_name='Cel i produkty')),
                ('komentarz', models.CharField(blank=True, default='', max_length=400, verbose_name='Komentarz')),
                ('link_do_ezz', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Link do EZZ')),
                ('odtworzeniowy', models.BooleanField(blank=True, default=False, verbose_name='Odtworzeniowy')),
                ('rozwojowy', models.BooleanField(blank=True, default=False, verbose_name='Rozwojowy')),
                ('planowany_termin_platnosci', models.CharField(blank=True, default='', max_length=81, verbose_name='Planowany termin płatności')),
                ('waluta', models.CharField(blank=True, default='PLN', max_length=7, verbose_name='Waluta')),
                ('budzet_capex_netto', models.FloatField(blank=True, default=0, null=True, verbose_name='Budżet CAPEX netto')),
                ('budzet_opex_netto', models.FloatField(blank=True, default=0, null=True, verbose_name='Budżet OPEX netto')),
                ('id_sap', models.CharField(blank=True, default='', max_length=60, verbose_name='ID SAP')),
                ('dostawca', models.CharField(blank=True, default='', max_length=191, verbose_name='Dostawca')),
                ('komentarz_akceptujacego', models.CharField(blank=True, default='', max_length=300, verbose_name='Komentarz akceptującego')),
                ('wymagana_data_zawarcia_umowy', models.DateField(blank=True, default=None, null=True, verbose_name='Wymagana data zawarcia umowy')),
                ('atrapa', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Atrapa')),
                ('acceptors', models.ManyToManyField(blank=True, default=None, to='general.acceptor', verbose_name='Akceptorzy')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.clients', verbose_name='Klient')),
                ('crip_id', models.ManyToManyField(blank=True, default=None, to='general.crip', verbose_name='Pozycje CRIP')),
                ('ezz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.ezz', verbose_name='Wniosek EZZ')),
                ('log', models.ManyToManyField(blank=True, default=None, to='purchases.logpurchase', verbose_name='Logi')),
                ('need', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='needs.needs', verbose_name='Potrzeba')),
                ('osoba_prowadzaca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Osoba prowadząca')),
                ('pilnosc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.pilnosc', verbose_name='Pilność')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.sections', verbose_name='Dział')),
                ('sposob_wyceny', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.sposob_wyceny', verbose_name='Sposób wyceny')),
                ('sposob_zakupu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.sposob_zakupu', verbose_name='Sposób zakupu')),
                ('status_akceptacji', models.ForeignKey(default=purchases.models.domyslny_status_akceptacji, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.status_akceptacji', verbose_name='Status akceptacji')),
                ('status_procesu', models.ForeignKey(default=purchases.models.domyslny_status_roboczy, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.status_procesu', verbose_name='Status procesu')),
                ('zgodnosc_mapy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.zgodnosc_mapy', verbose_name='Zgodność mapy')),
            ],
            options={
                'verbose_name': 'Zakup',
                'verbose_name_plural': 'Zakupy',
            },
        ),
    ]
