# Generated by Django 5.0.3 on 2024-12-08 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('needs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusIdei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Status idei',
                'verbose_name_plural': 'Statusy idei',
            },
        ),
        migrations.CreateModel(
            name='LogIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akcja', models.CharField(default=None, max_length=303, null=True, verbose_name='Akcja')),
                ('data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Log idei',
                'verbose_name_plural': 'Logi idei',
            },
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=2000, verbose_name='Temat')),
                ('czy_dotyczy_architektury', models.BooleanField(blank=True, default=True, null=True, verbose_name='Czy dotyczy architektury?')),
                ('data_utworzenia', models.DateField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('komentarz', models.CharField(blank=True, default=None, max_length=425, null=True, verbose_name='Komentarz')),
                ('wymagana_data_realizacji', models.DateField(blank=True, default=None, null=True, verbose_name='Wymagana data realizacji')),
                ('orientacynjy_budzet', models.FloatField(blank=True, default=0, max_length=19, null=True, verbose_name='Orientacyjny budżet')),
                ('osoba_kontakowa_u_klienta', models.CharField(blank=True, default=None, max_length=53, null=True, verbose_name='Osoba kontaktowa u klienta')),
                ('do_kiedy_zawieszona', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Do kiedy zawieszona?')),
                ('opis', models.CharField(blank=True, default=None, max_length=2301, null=True, verbose_name='Opis')),
                ('uzasadnienie', models.CharField(blank=True, default=None, max_length=2503, null=True, verbose_name='Uzasadnienie')),
                ('wlasciciel_biznesowy', models.CharField(blank=True, default=None, max_length=85, null=True, verbose_name='Właściciel biznesowy')),
                ('produkty', models.CharField(blank=True, default=None, help_text='Opis produktów, które zostaną wytworzone w wyniku realizacji pomysłu', max_length=1986, null=True, verbose_name='Produkty')),
                ('komentarz_akceptujacego', models.CharField(blank=True, default='', max_length=300, verbose_name='Komentarz akceptującego')),
                ('komentarz_architekta', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Komentarz architekta')),
                ('odpowiedz_koordynatora_do_architekta', models.CharField(blank=True, default='', max_length=2997, null=True, verbose_name='Odpowiedź koordynatora do architekta')),
                ('atrapa', models.CharField(blank=True, default='', max_length=2, null=True, verbose_name='Atrapa')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.clients', verbose_name='Klient')),
                ('inicjator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idea_inicjator', to=settings.AUTH_USER_MODEL, verbose_name='Inicjator')),
                ('needs', models.ManyToManyField(blank=True, default=None, to='needs.needs', verbose_name='Potrzeby')),
                ('osoba_prowadzaca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idea_koordynator', to=settings.AUTH_USER_MODEL, verbose_name='Osoba prowadząca')),
                ('powiazane_idee', models.ManyToManyField(blank=True, to='ideas.ideas', verbose_name='Powiązane idee')),
                ('priorytet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.priorytet_inicjatywy', verbose_name='Priorytet')),
                ('proponowany_sposob_realizacji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.sposob_zakupu', verbose_name='Proponowany sposób realizacji')),
                ('rodzaj_inicjatywy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.rodzaj_inicjatywy', verbose_name='Rodzaj Inicjatywy')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.sections', verbose_name='Dział')),
                ('status_akceptacji', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.status_akceptacji', verbose_name='Status Akceptacji')),
                ('log', models.ManyToManyField(blank=True, default=None, to='ideas.logidea', verbose_name='Logi')),
                ('status_idei', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ideas.statusidei', verbose_name='Status Idei')),
            ],
            options={
                'verbose_name': 'Pomysł',
                'verbose_name_plural': 'Pomysły',
            },
        ),
    ]
