# Generated by Django 5.0.3 on 2024-12-08 14:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opiniujacy', models.CharField(default='', max_length=80)),
            ],
            options={
                'verbose_name': 'Opiniujący',
                'verbose_name_plural': 'Opiniujący',
            },
        ),
        migrations.CreateModel(
            name='Crip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crip_id', models.CharField(max_length=40)),
                ('nazwa_projektu', models.CharField(default='', max_length=700)),
                ('jednostka', models.CharField(default='', max_length=16, null=True)),
                ('sekcja', models.CharField(default='', max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'Crip',
                'verbose_name_plural': 'Cripy',
            },
        ),
        migrations.CreateModel(
            name='Dostepnosci_rozwiazania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poziom', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'SLA',
                'verbose_name_plural': 'SLA',
            },
        ),
        migrations.CreateModel(
            name='Klasyfikacja_zmiany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zmiana', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Klasyfikacja zmiany',
                'verbose_name_plural': 'Klasyfikacje zmiany',
            },
        ),
        migrations.CreateModel(
            name='MaileDoWyslania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Temat maila, który zostanie wysłany', max_length=200)),
                ('body', models.CharField(help_text='Treść maila, który zostanie wysłany', max_length=40000)),
                ('recipient', models.CharField(help_text='Adresat maila, który zostanie wysłany', max_length=100)),
                ('sender', models.CharField(default='avantic@pgnig.pl', help_text='Nadawca maila, który zostanie wysłany', max_length=100)),
            ],
            options={
                'verbose_name': 'Mail do wysłania',
                'verbose_name_plural': 'Maile do wysłania',
            },
        ),
        migrations.CreateModel(
            name='MeetingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parametry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='', max_length=40, null=True)),
                ('opis', models.CharField(default='', max_length=400, null=True)),
                ('num', models.IntegerField(default=0, null=True)),
                ('str', models.CharField(default='', max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Parametr',
                'verbose_name_plural': 'Parametry',
            },
        ),
        migrations.CreateModel(
            name='Pilnosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilnosc', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Pilność',
                'verbose_name_plural': 'Pilności',
            },
        ),
        migrations.CreateModel(
            name='Poziomy_dostepnosci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poziom', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Poziom dostępności',
                'verbose_name_plural': 'Poziomy dostępności',
            },
        ),
        migrations.CreateModel(
            name='Priorytet_inicjatywy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorytet_inicjatywy', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Priorytet inicjatywy',
                'verbose_name_plural': 'Priorytety inicjatyw',
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_text', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rodzaj_inicjatywy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_inicjatywy', models.CharField(default='', max_length=60)),
            ],
            options={
                'verbose_name': 'Rodzaj inicjatywy',
                'verbose_name_plural': 'Rodzaje inicjatyw',
            },
        ),
        migrations.CreateModel(
            name='Rodzaje_uslug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usluga', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Rodzaj usługi',
                'verbose_name_plural': 'Rodzaje usług',
            },
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('short_name', models.CharField(max_length=10)),
                ('manager', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Dział',
                'verbose_name_plural': 'Działy',
            },
        ),
        migrations.CreateModel(
            name='Sposob_wyceny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sposob_wyceny', models.CharField(default='', max_length=40)),
            ],
            options={
                'verbose_name': 'Sposób wyceny',
                'verbose_name_plural': 'Sposoby wyceny',
            },
        ),
        migrations.CreateModel(
            name='Sposob_zakupu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sposob_zakupu', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Sposób zakupu',
                'verbose_name_plural': 'Sposoby zakupu',
            },
        ),
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='', help_text='Nazwa zdarzenia', max_length=400, null=True)),
                ('opis', models.TextField(blank=True, help_text='Opis kontekstu zdarzenia')),
                ('czas_utworzenia', models.DateTimeField(default=django.utils.timezone.now, help_text='Dokładny czas utworzenia')),
                ('sekwencja', models.CharField(blank=True, help_text='Opcjonalna sekwencja, do której należy dany rekord', max_length=100)),
                ('czas_trwania', models.DurationField(blank=True, help_text='Czas trwania operacji', null=True)),
                ('typ_zdarzenia', models.CharField(blank=True, help_text='Rodzaj lub kategoria zdarzenia, np. "database", "IO", "CPU"', max_length=100)),
            ],
            options={
                'ordering': ['czas_utworzenia'],
            },
        ),
        migrations.CreateModel(
            name='Status_akceptacji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akceptacja', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Status akceptacji',
                'verbose_name_plural': 'Statusy akceptacji',
            },
        ),
        migrations.CreateModel(
            name='Status_procesu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Status procesu',
                'verbose_name_plural': 'Statusy procesu',
            },
        ),
        migrations.CreateModel(
            name='uslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=100, null=True)),
                ('nazwa', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, default='', help_text='Nazwa zmiennej', max_length=200)),
                ('wartosc', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zapytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(default='', max_length=400, null=True)),
                ('tresc', models.CharField(default='', max_length=2400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zgodnosc_mapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zgodnosc_mapy', models.CharField(default='', max_length=40)),
            ],
            options={
                'verbose_name': 'Zgodność mapy',
                'verbose_name_plural': 'Zgodności map',
            },
        ),
        migrations.CreateModel(
            name='zlecenia_kontrolingowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=100, null=True)),
                ('nazwa', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('short_name', models.CharField(default='', max_length=10)),
                ('opiekun', models.ForeignKey(default=None, limit_choices_to={'groups__name': 'idea_allocator', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients_opiekun', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='clients_custom_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_resolution', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('meeting_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('creation_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('sort_field', models.CharField(choices=[('id', 'ID'), ('section', 'Sekcja'), ('client', 'Klient')], default='id', max_length=50)),
                ('sort_order', models.CharField(choices=[('asc', 'Rosnąco'), ('desc', 'Malejąco')], default='asc', max_length=4)),
                ('attendance_list', models.ManyToManyField(blank=True, related_name='meeting_attendance', to=settings.AUTH_USER_MODEL)),
                ('invitations', models.ManyToManyField(blank=True, related_name='meeting_invitations', to=settings.AUTH_USER_MODEL)),
                ('meeting_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.meetingstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=400, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notatka',
                'verbose_name_plural': 'Notatki',
            },
        ),
        migrations.CreateModel(
            name='Planowane_zakupy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=None, max_length=5000, null=True)),
                ('budzet', models.FloatField(default=0, max_length=19, null=True)),
                ('wymagana_data_realizacji', models.DateField(default=None, null=True)),
                ('wymagana_data_zawarcia_umowy', models.DateField(default=None, null=True)),
                ('EZZ_number', models.CharField(default=None, max_length=20, null=True)),
                ('waluta', models.CharField(default='PLN', max_length=7, null=True)),
                ('budzet_capex_netto', models.FloatField(default=0, null=True)),
                ('budzet_opex_netto', models.FloatField(default=0, null=True)),
                ('dostawca', models.CharField(default='', max_length=191, null=True)),
                ('odtworzeniowy', models.BooleanField(default=False, null=True)),
                ('rozwojowy', models.BooleanField(default=False, null=True)),
                ('osoba_prowadzaca', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
