# Generated by Django 5.0.3 on 2024-12-01 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('ideas', '0001_initial'),
        ('needs', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planowane_zakupy',
            name='pomysl',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='ideas.ideas'),
        ),
        migrations.AddField(
            model_name='planowane_zakupy',
            name='potrzeba',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='needs.needs'),
        ),
        migrations.AddField(
            model_name='planowane_zakupy',
            name='zakup',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.purchases'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idea_resolutions', to='ideas.ideas'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='general.meeting'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='need',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='need_resolutions', to='needs.needs'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='discussed_ideas',
            field=models.ManyToManyField(blank=True, related_name='meeting_ideas', through='general.Resolution', to='ideas.ideas'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='discussed_needs',
            field=models.ManyToManyField(blank=True, related_name='meeting_needs', through='general.Resolution', to='needs.needs'),
        ),
        migrations.AddField(
            model_name='planowane_zakupy',
            name='rodzaj_inicjatywy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.rodzaj_inicjatywy'),
        ),
        migrations.AddField(
            model_name='sections',
            name='kierownik',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections_kierownik', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sections',
            name='users',
            field=models.ManyToManyField(related_name='custom_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planowane_zakupy',
            name='section',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='general.sections'),
        ),
        migrations.AddField(
            model_name='planowane_zakupy',
            name='sposob_wyceny',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.sposob_wyceny'),
        ),
        migrations.AddField(
            model_name='planowane_zakupy',
            name='sposob_zakupu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='general.sposob_zakupu'),
        ),
        migrations.AddIndex(
            model_name='stamp',
            index=models.Index(fields=['sekwencja'], name='general_sta_sekwenc_d11445_idx'),
        ),
        migrations.AddIndex(
            model_name='stamp',
            index=models.Index(fields=['czas_utworzenia'], name='general_sta_czas_ut_201816_idx'),
        ),
        migrations.AddField(
            model_name='zapytanie',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
